from abc import ABC,abstractmethod
from uuid import UUID
from supplymind.features.knowledge.domain.entities import EnterpriseDocument
class DocumentRegistryRepository(ABC):
 @abstractmethod
 async def add(self,document:EnterpriseDocument)->EnterpriseDocument: ...
 @abstractmethod
 async def get_by_checksum(self,checksum:str)->EnterpriseDocument|None: ...
 @abstractmethod
 async def update_status(self,document_id:UUID,*,status:str,chunk_count:int)->EnterpriseDocument: ...
 @abstractmethod
 async def list_recent(self,*,limit:int=100)->list[EnterpriseDocument]: ...
