FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml README.md ./
COPY src ./src
COPY apps ./apps
COPY migrations ./migrations
COPY alembic.ini ./
COPY models ./models
RUN pip install --no-cache-dir -U pip && pip install --no-cache-dir -e .
ENV PYTHONUNBUFFERED=1
CMD ["sh","-c","alembic upgrade head && uvicorn apps.api.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
